this.Ninja.module('$pallete', [], function () {
  
  return {
    
    'COLOR_MASTER_DARKING': '#000000',
    'COLOR_MASTER_DARKEST': '#0A0A0A',
    'COLOR_MASTER_DARKER': '#1A1A1A',
    'COLOR_MASTER_DARK': '#2C2C2C',
    'COLOR_MASTER': '#626262',
    'COLOR_MASTER_LIGHT': '#E6E6E6',
    'COLOR_MASTER_LIGHTER': '#F0F0F0',
    'COLOR_MASTER_LIGHTEST': '#FAFAFA',
    'COLOR_MASTER_LIGHTING': '#FFFFFF',
    
    'COLOR_PRIMARY_DARKER': '#413768',
    'COLOR_PRIMARY_DARK': '#5B4D91',
    'COLOR_PRIMARY': '#6D5CAE',
    'COLOR_PRIMARY_LIGHT': '#8A7DBE',
    'COLOR_PRIMARY_LIGHTER': '#E2DEEF',
    
    'COLOR_COMPLETE_DARKER': '#2B6A94',
    'COLOR_COMPLETE_DARK': '#3C93CE',
    'COLOR_COMPLETE': '#48B0F7',
    'COLOR_COMPLETE_LIGHT': '#6DC0F9',
    'COLOR_COMPLETE_LIGHTER': '#DAEFFD',
    
    'COLOR_SUCCESS_DARKER': '#0A7C71',
    'COLOR_SUCCESS_DARK': '#0DAD9E',
    'COLOR_SUCCESS': '#10CFBD',
    'COLOR_SUCCESS_LIGHT': '#40D9CA',
    'COLOR_SUCCESS_LIGHTER': '#CFF5F2',
    
    'COLOR_WARNING_DARKER': '#957D32',
    'COLOR_WARNING_DARK': '#CFAE45',
    'COLOR_WARNING': '#F8D053',
    'COLOR_WARNING_LIGHT': '#F9D975',
    'COLOR_WARNING_LIGHTER': '#FEF6DD',
    
    'COLOR_DANGER_DARKER': '#933432',
    'COLOR_DANGER_DARK': '#CD4945',
    'COLOR_DANGER': '#F55753',
    'COLOR_DANGER_LIGHT': '#F77975',
    'COLOR_DANGER_LIGHTER': '#FDDDDD',
    
    'COLOR_INFO_DARKER': '#232B31',
    'COLOR_INFO_DARK': '#313B44',
    'COLOR_INFO': '#3B4752',
    'COLOR_INFO_LIGHT': '#626C75',
    'COLOR_INFO_LIGHTER': '#D8DADC'
    
  };
  
});